### PR TITLE
Fix "OverflowError Python int too large for C long" on Windows 7 64bits.

### PR DESCRIPTION
**Pull request by jcardonnet**
"dtype" parameter on "numpy.random.RandomState.randint" requires numpy 1.11 or greater.

### CODE REVIEW

**Comment by ekzhu** [comment]
Thanks for the input! Greatly appreciated. I don't have a windows machine so I can't really test if it works. However the unit test failed. I think a few more changes is still required. Do you want to make the changes?

Perhaps the easiest way is to make sure all numpy array initializations and constants use int64 / uint64 explicitly. 64-bit is needed because the [computation of the permutation functions](https://github.com/ekzhu/datasketch/blob/master/datasketch/minhash.py#L106) may cause 32-bit int to overflow. This can happen on Windows since the default "int" means 32-bit.

Another note: there are few places in `minhash.py` that involves initializing the hash value numpy array. So a good fix may includes writing a new function that does the initialization and using it everywhere.

**Comment by jcardonnet** [comment]
Sure, I'd be happy to make the changes. All tests passed on Win 7 64bits but I can test also it on CentOS 6.7 64bits, OS X Yosemite and Win 10 64bits to see what other changes might be required.

**Comment by ekzhu** [comment]
Thanks a lot!

**Comment by ekzhu** [comment]
How's the change going?

**Comment by ekzhu** [comment]
This should be fixed now.

**Pull request closed without merging**
