### PR TITLE
Add Cassandra storage layer

### PR DESCRIPTION
**Pull request by ostefano**
This is a storage layer that uses Cassandra as a backend. It is optimized to take into account Cassandra internals and its (intrinsic) limitations (see for example how all the keys are retrieved and how the list abstraction is implemented). I have also added a new batch of tests to both `TestMinHashLSH` and `TestWeightedMinHashLSH`. Since Cassandra is required (Cassandra is not mocked) they can be enabled by flipping the `DO_TEST_CASSANDRA` variable.

### CODE REVIEW

**Comment by ostefano** [comment]
@ekzhu the integration tests are failing on python2.7 on an unrelated test. Can you give it a look and let me know if there is anything I can do to fix it, or if shall I just rebase at some point? Thanks!

**Comment by ostefano** [comment]
Must have been a fluke. Retriggering the build worked.

**Comment by ekzhu** [comment]
Thanks for the pull request! Sorry for the delay please give me some time to look at it.

**Comment by ekzhu** [comment]
One way to enable Cassandra in travis build test is to use a default Cassendra service: https://docs.travis-ci.com/user/database-setup/#cassandra. Do you think it is a good idea to run the tests in travis? 

The project's setup.py file and dependency management (redis, mongo, and now cassandra) is a bit messy... my fault. Let me fix that in the next couple of days and I will try to merge this pull request.

**Comment by ostefano** [comment]
@ekzhu mmm, that didn't work. I am reverting for now. Let me know if there is anything else I need to modify.

**Comment by ostefano** [comment]
@ekzhu I played a bit in my branch, and it seems that if we want to enable the Cassandra service there is a fair amount of tweaking needed: http://davidemoro.blogspot.com/2019/02/setup-cassandra-service-travisci.html

Let me know if we should go this way.

**Comment by ekzhu** [comment]
@ostefano I think it would be quite useful if we can run this test on Travis. It would be great if we can skip Cassandra tests by default when we run it locally.

**Comment by ekzhu** [comment]
I cleaned up the `test` directory so we can use `nosetests` to run all tests locally. Could you move the canssandra related tests into a separate module file `test/test_lsh_cassandra.py`?

To skip Cassandra tests you can set 

`DO_TEST_CASSANDRA = os.environ.get("DO_TEST_CASSANDRA") == "true"`

And in `.travis.yml` use `export DO_TEST_CASSANDRA=true'` before running `nosetests test.test_lsh_cassandra`.

**Comment by ostefano** [comment]
Sounds good. Will send another iteration later today.

**Comment by ostefano** [comment]
@ekzhu done.

**Comment by ekzhu** [comment]
Thanks! I just realized that in order for people to notice this exciting new feature, we also need to have some documentation. Right now the documentation for MinHashLSH (http://ekzhu.com/datasketch/lsh.html#minhash-lsh-at-scale) only includes the Redis and MongoDB storage layer. It would be great if you can add documentation for Cassandra. An example configuration with all parameters explained would be extremely useful.

**Comment by ostefano** [comment]
Sure, can do.

**Comment by ekzhu** [comment]
Thanks! The documentation source is in https://github.com/ostefano/datasketch/blob/cassandra/docsrc/lsh.rst

**Comment by ostefano** [comment]
@ekzhu done. I have also compiled the sources and committed the latest version. Let me know if you want me to revert this last part.

**Comment by ekzhu** [comment]
@ostefano this is fantastic! Does the cassandra storage config make use of the `basename` parameter that allows connection to existing storage? Or is this functionality handled by `keyspace`?

**Comment by ostefano** [comment]
@ekzhu fair point. I have amended the change-set to describe that specific option as well.

**Comment by ostefano** [comment]
Mmm, annoying network fluke. Re-triggering.

**Comment by ekzhu** [comment]
Thanks a lot! I have merged the pull request and the code will appear in version 1.5.0.

**Pull request merged**
