### PR TITLE
Implement #123 arbitrary Mongo URL & collection name

### PR DESCRIPTION
**Pull request by ekevoo**
I have also updated the documentation a bit.

The purpose of the function `AsyncIOMotorClient.get_default_database` is to allow for the Mongo URL to define a database. If the URL contains a database, that database in the URL will be used, otherwise, the calculated database name is used. As for `get_collection`, I changed it for consistency only.

I wanted to update the unit tests, but they were skipped… and when I tried to un-skip them everything failed spetacularly. I'm not sure what to do about that.

Cheers!

### CODE REVIEW

**Comment by ekzhu** [comment]
Thanks for the pull request. @aastafiev I remember the unit test for Mongo was skipped because of Python version incompatibility?

**Comment by aastafiev** [comment]
Hi,

You are right. We skipped them because of 2.7-3.5 python incompatibility. Could we write python version check for skipping tests?


---------------------
Sincerely yours,
Aleksey Astafiev

**Comment by ekevoo** [comment]
Yes, it's in `sys.version_info`.

**Comment by ekzhu** [comment]
@ekevoo So is your unit tests failure caused by Python version issue?

**Comment by ekevoo** [comment]
Turns out the check was already there:

```
@unittest.skipIf(sys.version_info < (3, 6), "Skipping TestAsyncMinHashLSH. Supported Python version >= 3.6")
```

Travis had accepted the changes. I initially didn't try very hard to run unit tests, it turns out that they do require a running MongoDB server to run, which is a little problematic, but I'm not qualified to fix. So I just ran a local server and created new tests to test my changes. Everything passed for me, I hope Travis agrees.

**Comment by ekzhu** [comment]
Thanks @ekevoo!

**Comment by ekevoo** [comment]
Thank you too! @ekzhu and @aastafiev! :) Can you tell when you might next release it?

**Comment by ekzhu** [comment]
I already have. https://pypi.org/project/datasketch/1.5.1/#history 🚢

**Comment by ekevoo** [comment]
Ah, I was checking the releases tab instead. 😅
Thank you very much ✌️

**Comment by ekevoo** [comment]
Hi, the version that was published on PIP as 1.5.1 doesn't contain this.

**Comment by ekzhu** [comment]
Are you sure? I just checked [this source distribution](https://files.pythonhosted.org/packages/9b/33/fd79cb9e1f686ffce4fb9c50b21d7425f06546dc10628449f979e726a1fe/datasketch-1.5.1.tar.gz) and I can see the new code in there.

**Comment by ekevoo** [comment]
I am sure. When I pip install, that's the address I get instead.

https://files.pythonhosted.org/packages/e9/7a/975274a59ab7e0117a8304ae97220b5800d31f69813c97753a79239dabac/datasketch-1.5.1-py2.py3-none-any.whl

**Comment by ekzhu** [comment]
Thanks. Could you show a simple script that demonstrate it? I don't have Mongo Atlas.

**Comment by ekevoo** [comment]
That's okay, you can test using local mongo with the new URL feature.

```
storage_config={"type": "aiomongo",
                "mongo": {"url": "mongodb://localhost/databaseName"}}
```

**Pull request merged**
