### PR TITLE
Support asyncio redis

### PR DESCRIPTION
**Pull request by long2ice**

### CODE REVIEW

**Comment by ekzhu** [comment]
@long2ice  thanks for the pull request! There seems to be a minor bug related to importlib changes in Python 3.8. See: https://stackoverflow.com/questions/59216175/importerror-cannot-import-name-metadata-from-importlib

**Comment by long2ice** [comment]
Fixed

**Comment by ekzhu** [comment]
It looks like the bug is still there:

==================================== ERRORS ====================================
_________________ ERROR collecting test/aio/test_lsh_mongo.py __________________
ImportError while importing test module '/home/runner/work/datasketch/datasketch/test/aio/test_lsh_mongo.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.6.[15](https://github.com/ekzhu/datasketch/runs/6998453721?check_suite_focus=true#step:9:16)/x64/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/aio/test_lsh_mongo.py:15: in <module>
    from datasketch.experimental.aio.lsh import AsyncMinHashLSH
datasketch/experimental/__init__.py:[18](https://github.com/ekzhu/datasketch/runs/6998453721?check_suite_focus=true#step:9:19): in <module>
    from datasketch.experimental.aio.lsh import AsyncMinHashLSH
datasketch/experimental/aio/lsh.py:11: in <module>
    from datasketch.experimental.aio.storage import (async_ordered_storage, async_unordered_storage, )
datasketch/experimental/aio/storage.py:2: in <module>
    from importlib import metadata
E   ImportError: cannot import name 'metadata'

**Comment by long2ice** [comment]
Sorry, fixed again

**Comment by ekzhu** [comment]
Thanks @long2ice . The issue is fixed. Would you mind add some documentation for this new feature? Currently the documentation only covers examples using MongoDB's Async IO API. It would be great to have a Redis version as well. This will increase the visibility of this new feature. 

The current documentation on Async IO: http://ekzhu.com/datasketch/lsh.html#asynchronous-minhash-lsh-at-scale

The documentation source for this page: https://github.com/ekzhu/datasketch/blob/master/docs/lsh.rst

**Comment by long2ice** [comment]
OK, I will do it

**Comment by long2ice** [comment]
Done

**Comment by ekzhu** [comment]
Thank you!

**Pull request merged**
