### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by Sinusoidal36**
I've made some performance improvements in the MinHash class and added a helper method for bulk computation.

1. Precasting _mersenne_prime and _max_hash, they don't need to be cast multiple times.
2. I've modified the update method to accept a list of bytes so hash values can be computed in batches. This avoids using for loops in python space and packs all those operations into the numpy calls once. Only caveat here is that the matrix operations use more memory and you should do chunking if you're dealing with huge sets.
3. The bulk helper removes unnecessary initialization overhead of the permutations and initial hashvalues. They are computed once then passed on to new MinHash objects as they are produced.

These changes give some pretty nice performance improvements, up to 3X for updates, and anywhere from 5-25X for bulk computing. [See my benchmark gist here](https://gist.github.com/Sinusoidal36/393b0aa6d73dfbd907933e750476e1b7)

### CODE REVIEW

**Comment by ekzhu** [comment]
I really like this pull request. Thank you!

The bulk update strategy is great to avoid for-looping. Although in many scenarios the raw data (e.g., string tokens) are already scanned in a Python for-loop while converting into bytes and inserted, so the for-lopping cannot be avoided. I can imaging in some scenario the data is bulk-processed using Pandas/Dask/others -- is this a common scenario?

**Comment by Sinusoidal36** [comment]
My pleasure, thanks for the awesome python package. I use it frequently to great effect.

> so the for-lopping cannot be avoided
The primary optimization here is updating the hash values in batch. The string encoding is a negligible operation in comparison and can be done before passing the entire set of elements in to the update method at once. This way we can fully take advantage of numpy during the matrix operations.

> As mentioned in #143 (comment) do you think the additional lines of code in the critical path slows the overall speed down a little bit (when using the iterative version)?
I didn't test the impact of the type check, but it certainly has _some_ negative effect. My intuition is that the hash value calculation dominates the method call and any regression caused by the type check would be minimal. However, we can split the batch approach out into a new method update_batch()? to avoid any impact.

**Comment by ekzhu** [comment]
Thanks for the explanation. I understand the benefit now. Hashing individual values are often quite costly and batching is a great way going forward consider memory is often under-utilized.

> we can split the batch approach out into a new method update_batch()? to avoid any impact.

Yes. I think this would be a good idea also because it makes the interface more clear.

**Comment by Sinusoidal36** [comment]
I reverted a couple of changes and moved the batch update to its own method. Bulk helper should be a bit cleaner now, using the already implemented copy method in the MinHash class. I managed to eek out some more performance from the batch update, [here is the new benchmark](https://gist.github.com/Sinusoidal36/5094341c5dd4a2ddddedfacd191ec55a). Now up to 4.5X for updates and 7-25X for bulk computing.

**Comment by Sinusoidal36** [comment]
Anything else needed to merge this and #143 ?

**Comment by ekzhu** [comment]
Thanks for the changes. Now from the test examples it feel like `bulk.compute_minhashes` the interface is a bit counter-intuitive as a initialized MinHash object is passed as an argument. Maybe use generic keyword arguments and pass them directly to the underlying MinHash constructor? E.g.:

```python
def compute_minhashes(data, **minhash_kwargs):
    ...
    # Initialize individual minhash here using the keyword arguments from above.
    MinHash(**minhash_kwargs)
```

**Comment by Sinusoidal36** [comment]
You're right, that's a better approach. Pushed the suggested changes.

**Comment by ekzhu** [comment]
Thanks for the changes. Right now we have a stand-alone module `bulk` that only works for MinHash. Would you consider moving the method `compute_minhashes` as a `@staticmethod` of the MinHash class and make the helper function private (i.e., add "_" in front of the name). This helps to increase the awareness of the feature as it will appear in the API doc for the MinHash class.

For users to be aware of this feature, would you consider writing small section in https://github.com/ekzhu/datasketch/blob/master/docs/minhash.rst with an example to show case this new feature? Some plots from your benchmarks can be great to show the benefit in saving compute cost. Kindly also include this discussion thread in the doc to provide some historical context.

**Comment by ekzhu** [comment]
I made the above changes to save your time :)

**Comment by Sinusoidal36** [comment]
Cool, thanks! I've been bogged down with other things, been meaning to get to it. Your changes look good. I'll try to set some time to provide those docs you asked.

**Pull request merged**
