### PR TITLE
Support numpy>=1.20.0

### PR DESCRIPTION
**Pull request by joehalliwell**
`numpy.int` was only ever an alias for the built-in, and was deprecated from version 1.20.0

See: https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated

### CODE REVIEW

**Review by ekzhu — APPROVED** [review]

**Comment by joehalliwell** [comment]
Not sure why the python-setup step was failing, but I figured it wouldn't hurt to update it.

**Comment by LouisTrezzini** [comment]
Thanks for working on this change! Do you have plans to merge the PR and push a new release?

**Comment by joehalliwell** [comment]
@ekzhu Thanks for fixing the build and merging this. (I wasn't able to trigger a build, so it was just too painful to work on the actions stuff :smiling_face_with_tear: )

**Comment by ekzhu** [comment]
> @ekzhu Thanks for fixing the build and merging this. (I wasn't able to trigger a build, so it was just too painful to work on the actions stuff 🥲 )

Indeed 
Lots of issues with running Cassandra container in github action. Not related to the code though.

**Pull request merged**
